# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 351a18ab41b10f5e1300fb575e10ab7d2cbf1fae72846f44ea19b886cf6928885d9bad1793056f36f2765afa55ed2798d7ddf54b0468b9ed9bf9b202e4b55a67

test:
  secret_key_base: 921eb8ba1d050ced4272984cfc91d449e764d0c7d8a36195c3f480de42b2a2df325726b9c622fe2e00af3ca19ef06d36954b656e301b798f0ca5f221d222c4c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
